# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "30 21 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Login to DockerHub
  inputs:
    command: login
    containerRegistry: dockerhub-nddevops

- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    repository: netzding/clamav
    tags: latest

- task: Docker@2
  displayName: Logout of DockerHub
  inputs:
    command: logout
    containerRegistry: dockerhub-nddevops
